### PR TITLE
Add a new examples repo

### PR DESCRIPTION
**Pull request by ladatz**
Add a chariott-example-applications repo

### CODE REVIEW

**Comment by netomi** [comment]
Change looks good to me, just requiring an approval from a project lead.

**Comment by netomi** [comment]
Each project handles  approvals differently, need to think about ways to let each project decide and formalize how they would like to have approval for changes, e.g. project lead approval, committer approval or just EF approval if request is made from a committer.

**Review by netomi — APPROVED** [review]

**Comment by ladatz** [comment]
Yes, it would be good if we had the ability to merge this change since I am a committer. When we requested our last repo (Agemo) to be created, I am pretty sure we only needed a committer to request the change (see this issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3355). Our project lead is on vacation right now. I can get approval from another committer later today

**Comment by netomi** [comment]
change has been applied, repo has been created.

**Pull request merged**
